apiVersion: v1
kind: Service
metadata:
  name: login
  namespace: go-x
  labels:
    app: login
spec:
  type: NodePort
  ports:
    - port: 8000
      nodePort: 30100
  selector:
    app: login

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login
  namespace: go-x
  labels:
    app: login
spec:
  selector:
    matchLabels:
      app: login
  replicas: 3
  template:
    metadata:
      labels:
        app: login
    spec:
      serviceAccountName: sa-go-x
      containers:
      - name: login
        image: fananchong/go-x
        imagePullPolicy: Always
        command: [ "./login", "--cfg=config.toml" ]
        ports:
        - containerPort: 8080



