[common]
Version = "0.0.1"
LogDir = "./logs"
LogLevel = 0
Debug = true
IntranetToken = "6d8f1f3a-739f-47fe-9ed1-ea39276cd10d"

[dbaccount]
Name = "account"
Addrs = ["101.132.47.70:39379", "101.132.47.70:39381", "101.132.47.70:39383"]
Password = ""
DBIndex = 0

[dbtoken]
Name = "token"
Addrs = ["101.132.47.70:39379", "101.132.47.70:39381", "101.132.47.70:39383"]
Password = ""
DBIndex = 0

[dbserver]
Name = "server"
Addrs = ["101.132.47.70:39379", "101.132.47.70:39381", "101.132.47.70:39383"]
Password = ""
DBIndex = 0

[login]
Listen = ":8080"
Sign1 = "5UY6$f$h"
Sign2 = "3wokZB%q"
Sign3 = "%2Fi9TRf"

[gateway]
Connect = [3, 5]            #1: login; 2: gateway; 3: lobby; 4: room; 5: hub


[lobby]

[hub]


[k8s]
	[k8s.login]
	t = 1
	ns = "go-x"
	svc = "login"

	[k8s.gateway]
	t = 2
	ns = "go-x"
	svc = "gateway"

	[k8s.Lobby]
	t = 3
	ns = "go-x"
	svc = "Lobby"

	[k8s.room]
	t = 4
	ns = "go-x"
	svc = "room"

	[k8s.hub]
	t = 5
	ns = "go-x"
	svc = "hub"
