[common]
Version = "0.0.1"
LogDir = "./logs"
LogLevel = 0
Debug = true

[etcd]
Hosts = ["101.132.47.70:12379", "101.132.47.70:22379", "101.132.47.70:32379"]

[dbaccount]
Name = "account"
Addrs = ["101.132.47.70:39379", "101.132.47.70:39381", "101.132.47.70:39383"]
Password = ""
DBIndex = 0

[dbtoken]
Name = "token"
Addrs = ["101.132.47.70:39379", "101.132.47.70:39381", "101.132.47.70:39383"]
Password = ""
DBIndex = 0

[login]
Listen = ":8080"
Sign1 = "5UY6$f$h"
Sign2 = "3wokZB%q"
Sign3 = "%2Fi9TRf"

[Gateway]
ExternalIp = "127.0.0.1"    #完整格式为IP:PORT。不填PORT，则自动生产。
IntranetIp = "localhost"    #完整格式为IP:PORT。不填PORT，则自动生产。
Connect = [1]
