version: "3"
services:

  redis1:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "16379:6379"
    networks:
      - net
    command: redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --slave-announce-ip IP --slave-announce-port 16379
      
  redis2:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "26379:6379"
    networks:
      - net
    command: redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --slave-announce-ip IP --slave-announce-port 26379 --slaveof redis1 6379
    
  redis3:
    image: redis
    deploy:
      replicas: 1
      restart_policy:
        condition: none
    ports:
      - "36379:6379"
    networks:
      - net
    command: redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --slave-announce-ip IP --slave-announce-port 36379 --slaveof redis1 6379
    
    
networks:
  net:
