version: "3"
services:
    
  node1:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP1]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39379:6379"
      - "49379:16379"
    volumes:
      - data1:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP1 --cluster-announce-port 39379 --cluster-announce-bus-port 49379 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"

  node2:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP2]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39380:6379"
      - "49380:16379"
    volumes:
      - data2:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP2 --cluster-announce-port 39380 --cluster-announce-bus-port 49380 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"

  node3:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP3]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39381:6379"
      - "49381:16379"
    volumes:
      - data3:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP3 --cluster-announce-port 39381 --cluster-announce-bus-port 49381 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"
    
  node4:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP4]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39382:6379"
      - "49382:16379"
    volumes:
      - data4:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP4 --cluster-announce-port 39382 --cluster-announce-bus-port 49382 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"
    
  node5:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP5]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39383:6379"
      - "49383:16379"
    volumes:
      - data5:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP5 --cluster-announce-port 39383 --cluster-announce-bus-port 49383 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"
    
  node6:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP6]
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "39384:6379"
      - "49384:16379"
    volumes:
      - data6:/data
    networks:
      - net
    command: /bin/bash -c "redis-server --save "" --maxmemory 5gb --timeout 0 --tcp-keepalive 60 --bind 0.0.0.0 --cluster-announce-ip IP6 --cluster-announce-port 39384 --cluster-announce-bus-port 49384 --cluster-enabled yes --cluster-config-file nodes-6379.conf --cluster-node-timeout 15000"
    
networks:
  net:
volumes:
  data1:
  data2:
  data3:
  data4:
  data5:
  data6:
