apiVersion: v1
kind: Service
metadata:
  name: center
  namespace: go-x
  labels:
    app: center
spec:
  ports:
    - port: 30300
      name: ""
  clusterIP: None
  selector:
    app: center

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: center
  namespace: go-x
  labels:
    app: center
spec:
  serviceName: center
  selector:
    matchLabels:
      app: center
  replicas: 2
  template:
    metadata:
      labels:
        app: center
    spec:
      serviceAccountName: sa-go-x
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: center
        image: 127.0.0.1:5000/fananchong/go-x
        imagePullPolicy: Always
        command: [ "./center", "--common-loglevel=0" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace



